name: CI
'on':
  push:
    branches:
      - main
env:
  PAGES_BRANCH: gh-pages     
jobs:
  build-dita:
    name: Build DITA
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Build HTML5 using DITA-OT commands
        uses: dita-ot/dita-ot-action@master
        with:
         install : |
            # Run some arbitrary installation commands
            set -v
            apt-get update -q
            apt-get install -qy --no-install-recommends nodejs
            # nodejs -v
            # Install plugins
            dita install plugins/com.example.html5-custom-css.zip
            dita install fox.jason.extend.css   
            dita install net.infotexture.dita-bootstrap        
            dita install org.doctales.xmltask
            dita install https://github.com/jason-fox/fox.jason.prismjs/archive/master.zip
            echo 'Finished installing plugins.'
         build: |
           dita -i Docs/spm_navigation_sample.ditamap -o SPM_HTML5 -f markdown_gitbook --filter=Docs/cur_spm_test.ditaval:Docs/cur_spm802.ditaval:Docs/cur_base_spm800.ditaval --nav-toc=collapsible           
           echo 'Finished build.'

  gitbook:
    name: Gitbook
    runs-on: ubuntu-latest
    permissions:
      contents: write     
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12.18.2
      - name: Install gitbook
        run: |
          npm install -g gitbook-cli markdownlint-cli
          gitbook install && gitbook build
        shell: bash           

      - name: Setup Git
        run: |
          cd SPM_HTML5        
          git config --global user.name $GITHUB_ACTOR
          git config --global user.email '$GITHUB_ACTOR@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
    
      - name: Switch branch and move in _book
        run: |
          git fetch origin $PAGES_BRANCH
          git branch
          git checkout $PAGES_BRANCH
          cp -R ./_book/* .
          rm -dr ./_book
          
      - name: Add everything to Git and commit
        run: |
          git add .
          git commit -m "Gitbook publish"
          git push 
          echo 'Finished deploying the site.                  

