name: CI
'on':
  push:
    branches:
      - main
jobs:
  build-dita:
    name: Build DITA
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Build HTML5 using DITA-OT commands
        uses: dita-ot/dita-ot-action@master
        with:
         install : |
            # Run some arbitrary installation commands
            set -v
            apt-get update -q
            apt-get install -qy --no-install-recommends nodejs
            nodejs -v
            # Install npx for Pagefind search
            npm install -g npx
            npx pagefind
            echo 'Finished installing npm and npx.'

            # Install plugins
            dita install plugins/com.example.html5-custom-css.zip
            dita install fox.jason.extend.css   
            dita install net.infotexture.dita-bootstrap        
            dita install org.doctales.xmltask
            dita install https://github.com/jason-fox/fox.jason.prismjs/archive/master.zip
            echo 'Finished installing plugins.'
         build: |
           dita -i Docs/spm_navigation_sample.ditamap -o SPM_HTML5 -f html5-bootstrap --filter=Docs/cur_spm_test.ditaval:Docs/cur_spm802.ditaval:Docs/cur_base_spm800.ditaval --nav-toc=collapsible --args.html5.toc=spm_toc
           echo 'Finished build.'
      - name: Run pagefind for search
        run:
          npx pagefind --source SPM_HTML5 --serve        
      - name: Deploy to Github packages
        # only deploy when pushing to main
        if: ${{(github.event_name == 'push' || github.event_name == 'workflow_dispatch' ) && github.ref_name == 'main'}}
        run: |
          cd SPM_HTML5
          git config --global init.defaultBranch main
          pwd
          set -v
          git init
          git config user.name ${{ github.actor }}
          git config user.email ${{ github.actor }}@users.noreply.github.com
          git add .
          echo 'Add completed'.
          git commit -m "Deploy commit: ${{ github.sha }}"
          echo 'Commit completed.'
          git push -f https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}.git main:gh-pages
          echo 'Finished deploying the site.'

