name: CI
'on':
  push:
    branches:
      - main
jobs:
  build-dita:
    name: Build DITA
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Build HTML5 using DITA-OT commands
        uses: dita-ot/dita-ot-action@master
        with:
         install : |
            # Run some arbitrary installation commands
            apt-get update -q
            apt-get install -qy --no-install-recommends nodejs
            nodejs -v

            # Install plugins
            dita install fox.jason.extend.css
            dita install org.doctales.xmltask
            dita install fox.jason.prismjs
         build: |
           dita -i Docs/spm_navigation_sample.ditamap -o SPM_HTML5 -f html5 --filter=Docs/cur_spm_test.ditaval:Docs/cur_spm802.ditaval:Docs/cur_base_spm800.ditaval --nav-toc=full --args.cssroot=spm-docs-teamtest/Docs --args.css=dita-ot-doc.css --args.copycss=yes
            # Install plugins

      - name: Deploy to Github packages
        # only deploy when pushing to main
        if: ${{(github.event_name == 'push' || github.event_name == 'workflow_dispatch' ) && github.ref_name == 'main'}}
        run: |
          cd SPM_HTML5
          git config --global init.defaultBranch main
          pwd
          set -v
          git init
          git config user.name ${{ github.actor }}
          git config user.email ${{ github.actor }}@users.noreply.github.com
          git add .
          echo 'Add completed'.
          git commit -m "Deploy commit: ${{ github.sha }}"
          echo 'Commit completed.'
          git push -f https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}.git main:gh-pages
          echo 'Finished deploying the site.'

